### ISSUE TITLE
OKD4: api server produces output unparsable by urllib3

### ISSUE THREAD

**Issue by mmazur** [kubevirt/ansible-kubevirt-modules#263]
```
TASK [Create a blank PVC image] *************************************************************************************************************************************************************
task path: /home/mmazur/dev/ansible-kubevirt-modules/tests/playbooks/kubevirt_pvc.yml:19
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mmazur
<127.0.0.1> EXEC /bin/sh -c 'echo ~mmazur && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042 `" && echo ansible-tmp-1561643974.248798-270436959413042="` echo /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042 `" ) && sleep 0'
Using module file /home/mmazur/.local/lib/python3.7/site-packages/ansible/modules/cloud/kubevirt/kubevirt_pvc.py
<127.0.0.1> PUT /home/mmazur/.ansible/tmp/ansible-local-21229f2od_f7g/tmpvnbcc3rd TO /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042/AnsiballZ_kubevirt_pvc.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042/ /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042/AnsiballZ_kubevirt_pvc.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042/AnsiballZ_kubevirt_pvc.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/mmazur/.ansible/tmp/ansible-tmp-1561643974.248798-270436959413042/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 603, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 362, in _error_catcher
    yield
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 668, in read_chunked
    self._update_chunk_length()
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 607, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_kubevirt_pvc_payload_4jrpngod/__main__.py", line 455, in main
    module.execute_module()
  File "/tmp/ansible_kubevirt_pvc_payload_4jrpngod/__main__.py", line 447, in execute_module
    result['result'] = self._wait_for_creation(resource, result['result']['metadata']['uid'])
  File "/tmp/ansible_kubevirt_pvc_payload_4jrpngod/__main__.py", line 383, in _wait_for_creation
    for event in resource.watch(namespace=self.namespace, timeout=self.params.get('wait_timeout')):
  File "/home/mmazur/.local/lib/python3.7/site-packages/openshift/dynamic/client.py", line 224, in watch
    timeout_seconds=timeout
  File "/home/mmazur/.local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 134, in stream
    for line in iter_resp_lines(resp):
  File "/home/mmazur/.local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 47, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 696, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mmazur/.local/lib/python3.7/site-packages/urllib3/response.py", line 380, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_modes": [
                "ReadWriteOnce"
            ],
            "annotations": null,
            "api_key": null,
            "ca_cert": null,
            "cdi_source": {
                "blank": true
            },
            "client_cert": null,
            "client_key": null,
            "context": null,
            "force": false,
            "host": null,
            "kubeconfig": null,
            "labels": null,
            "merge_type": null,
            "name": "pvc-blank",
            "namespace": "default",
            "password": null,
            "proxy": null,
            "resource_definition": null,
            "selector": null,
            "size": "100Mi",
            "state": "present",
            "storage_class_name": null,
            "username": null,
            "validate_certs": null,
            "volume_mode": null,
            "volume_name": null,
            "wait": true,
            "wait_timeout": 300
        }
    },
    "msg": "('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))"
}
```

Same thing with many other tasks (e.g. `kubevirt_dv_vm.yaml` / TASK [Create a Cirros VM from a DataVolume]). Possibly CDI related?

**Comment by mmazur** [comment]
Also looks like it might case something to do with the underlying python-openshift library.

**Comment by mmazur** [comment]
A bit of relevant info:
```
[2019-07-01T10:41:24.282Z] # Collecting urllib3>=1.23 (from kubernetes~=9.0.0->openshift)
[2019-07-01T10:41:24.282Z] #   Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
[2019-07-01T10:41:24.282Z] # Collecting requests (from kubernetes~=9.0.0->openshift)
[2019-07-01T10:41:24.282Z] #   Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
```

Also a [full build log where this happens](https://kubevirt-master-stdci-production.apps.ovirt.org/blue/rest/organizations/jenkins/pipelines/kubevirt_ansible-kubevirt-modules_standard-check-pr/runs/144/nodes/106/log/).

**Comment by pkliczewski** [comment]
@mmazur is it still a valid issue?

**Comment by mmazur** [comment]
Yes, this is the same error as https://bugzilla.redhat.com/show_bug.cgi?id=1751744
